### ISSUE TITLE
[BUG] Docker 部署 3.11.2 更新 3.21.0 后启动访问报 502，回退 3.7.1 正常

### ISSUE THREAD

**Issue by sgpublic** [cnk3x/xunlei#163]
docker-compose 部署：

```yaml
version: "3"
services:
  xunlei:
    image: cnk3x/xunlei:3.11.2
    privileged: true
    container_name: xunlei
    network_mode: host
    environment:
      - XL_UID=1000
      - XL_GID=1000
      - XL_DASHBOARD_PORT=5056
      - XL_DEBUG=true
      - XL_PREVENT_UPDATE=false
    volumes:
      - /mnt/core/app/xunlei:/xunlei/data
      - /mnt/resource/Xunlei:/xunlei/downloads
    restart: unless-stopped
```

启动后 3.11.2 运行正常，更新 3.21.0 后启动访问报 502，日志如下：

```
...
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] get version list [] map[hour:17]
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] create client unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] VfsFactory.Register type:os label:
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] VfsFactory.Register type:smb label:
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] VfsFactory.Register type:alidrive label:withAlidrive
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] VfsFactory.Register type:webdav label:
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] VfsFactory.Register type:mount_fs label:
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/] > use config
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] NewStorageManager req:[rootPath:/var/packages/pan-xunlei-com/shares/迅雷/.drive/] mgr:&{storms:map[] deviceSpace: rootPath:/var/packages/pan-xunlei-com/shares/迅雷/.drive/ mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} encryptKeys:[] coreEncryptKey:5c14679171f7c150e32a1e78f967b08c kvCache:0xc00049bb68}
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] [device_space=&from_startup=9223372036854] > new drive start[]
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] init config
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] configEngine register globalconfig 3
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] configEngine register envconfig 2
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] configEngine register platformdetect 0
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] [device_space=&from_startup=9223372036854] > new drive finish[] cost:0.00s
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] configEngine start watch 4
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] configEngine watch self change
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] get config from platformConfig
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] [from_startup=0] > build version:5d916f14 loglevel: info
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] set log level: info
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] drive/config_merge.go:115  > get config from envConfig
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] storage/repair.go:470 [func_name=openStorm&trace_id=BpLnfgDs&pid=34&db_name=6c8497ab1ec13cc128c281abf114f576&func_st=06/27 17:27:22&db_size=65536] > openStorm start
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] [34][operation=app.Before&device_space=&from_startup=0]startService app.Before start
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] pan-cli/main.go:259  > with cookie map[]
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] panic: runtime error: invalid memory address or nil pointer dereference
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f358c]
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] 
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] goroutine 119 [running]:
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] gitlab.xunlei.cn/xlppc/pan-cli/pkg/download_runner.ProcessStat(0xc000145200)
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] 	/xunlei-pan-cli/pkg/download_runner/upload.go:134 +0x44c
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] created by gitlab.xunlei.cn/xlppc/pan-cli/pkg/commands.StartDeviceRunner
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] 	/xunlei-pan-cli/pkg/commands/runner.go:80 +0xb6
06/27 17:27:22 DBG [xunlei-pan-cli-launcher.amd64.1] report log {"fields":{"error":"exit status 2","panic":"panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f358c]\n\ngoroutine 119 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/download_runner.ProcessStat(0xc000145200)\n\t/xunlei-pan-cli/pkg/download_runner/upload.go:134 +0x44c\ncreated by gitlab.xunlei.cn/xlppc/pan-cli/pkg/commands.StartDeviceRunner\n\t/xunlei-pan-cli/pkg/commands/runner.go:80 +0xb6\n","report_type":"launcher"}}
06/27 17:27:22 DBG [xunlei-pan-cli-launcher.amd64.1] 
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] [panCliPid=34]Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: runtime error: invalid memory address or nil pointer dereference
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f358c]
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] 
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] goroutine 119 [running]:
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] gitlab.xunlei.cn/xlppc/pan-cli/pkg/download_runner.ProcessStat(0xc000145200)
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] 	/xunlei-pan-cli/pkg/download_runner/upload.go:134 +0x44c
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] created by gitlab.xunlei.cn/xlppc/pan-cli/pkg/commands.StartDeviceRunner
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] 	/xunlei-pan-cli/pkg/commands/runner.go:80 +0xb6
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2]  repErr:exit status 2
06/27 17:27:22 ERR [xunlei-pan-cli-launcher.amd64.2] start new version 3.21.0=>3.21.0 err:exit status 2
06/27 17:27:22 WRN [xunlei-pan-cli-launcher.amd64.2] launcher version error exit status 2 retry 1
06/27 17:27:22 INF [xunlei-pan-cli-launcher.amd64.2] write launcher pid to file /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid 22
06/27 17:27:23.04 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
06/27 17:27:23.04 INFO [file=/var/packages/pan-xunlei-com/target/ui/envconfig&error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}]read envconfig failed use default
06/27 17:27:23.04 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
06/27 17:27:23.04 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
06/27 17:27:23.04 INFO getEnvs succ PLATFORM=群晖
06/27 17:27:23.04 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
06/27 17:27:23.04 INFO getEnvs succ TLSInsecureSkipVerify=true
06/27 17:27:23.04 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.04 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
06/27 17:27:23.04 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins]getPluginPATH
06/27 17:27:23.04 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
06/27 17:27:23.04 INFO setDownloadAlias DriveFileMount :map[]
06/27 17:27:23.04 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
06/27 17:27:23.04 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
06/27 17:27:23.04 INFO start detect platform
06/27 17:27:23.05 INFO Detector.Detect envPlatform:群晖
06/27 17:27:23.05 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
2024/06/27 17:27:23 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/06/27 17:27:23 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
06/27 17:27:23.12 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
06/27 17:27:23.12 INFO [error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}&file=/var/packages/pan-xunlei-com/target/ui/envconfig]read envconfig failed use default
06/27 17:27:23.12 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
06/27 17:27:23.12 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
06/27 17:27:23.12 INFO getEnvs succ PLATFORM=群晖
06/27 17:27:23.12 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
06/27 17:27:23.12 INFO getEnvs succ TLSInsecureSkipVerify=true
06/27 17:27:23.12 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.12 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.12 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins]getPluginPATH
06/27 17:27:23.12 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
06/27 17:27:23.12 INFO setDownloadAlias DriveFileMount :map[]
06/27 17:27:23.12 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
06/27 17:27:23.12 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
06/27 17:27:23.12 INFO start detect platform
06/27 17:27:23.12 INFO Detector.Detect envPlatform:群晖
06/27 17:27:23.12 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
2024/06/27 17:27:23 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/06/27 17:27:23 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
06/27 17:27:23.18 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
06/27 17:27:23.18 INFO [error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}&file=/var/packages/pan-xunlei-com/target/ui/envconfig]read envconfig failed use default
06/27 17:27:23.18 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
06/27 17:27:23.18 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
06/27 17:27:23.18 INFO getEnvs succ PLATFORM=群晖
06/27 17:27:23.18 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
06/27 17:27:23.18 INFO getEnvs succ TLSInsecureSkipVerify=true
06/27 17:27:23.18 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
06/27 17:27:23.18 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.18 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins]getPluginPATH
06/27 17:27:23.18 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
06/27 17:27:23.18 INFO setDownloadAlias DriveFileMount :map[]
06/27 17:27:23.18 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
06/27 17:27:23.18 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
06/27 17:27:23.18 INFO start detect platform
06/27 17:27:23.19 INFO Detector.Detect envPlatform:群晖
06/27 17:27:23.19 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
2024/06/27 17:27:23 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/06/27 17:27:23 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
06/27 17:27:23 ERR [xunlei-pan-cli-launcher.amd64.2] [report=true&panCliPid=34]CheckProcess Signal err:os: process already finished
06/27 17:27:23.26 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
06/27 17:27:23.26 INFO [file=/var/packages/pan-xunlei-com/target/ui/envconfig&error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}]read envconfig failed use default
06/27 17:27:23.26 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
06/27 17:27:23.26 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
06/27 17:27:23.26 INFO getEnvs succ PLATFORM=群晖
06/27 17:27:23.26 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
06/27 17:27:23.26 INFO getEnvs succ TLSInsecureSkipVerify=true
06/27 17:27:23.26 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.26 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.26 INFO [use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins&report=true]getPluginPATH
06/27 17:27:23.26 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.26 INFO setDownloadAlias DriveFileMount :map[]
06/27 17:27:23.26 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
06/27 17:27:23.26 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
06/27 17:27:23.26 INFO start detect platform
06/27 17:27:23.26 INFO Detector.Detect envPlatform:群晖
06/27 17:27:23.26 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
2024/06/27 17:27:23 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/06/27 17:27:23 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
06/27 17:27:23.32 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
06/27 17:27:23.32 INFO [file=/var/packages/pan-xunlei-com/target/ui/envconfig&error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}]read envconfig failed use default
06/27 17:27:23.32 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
06/27 17:27:23.32 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
06/27 17:27:23.32 INFO getEnvs succ PLATFORM=群晖
06/27 17:27:23.32 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
06/27 17:27:23.32 INFO getEnvs succ TLSInsecureSkipVerify=true
06/27 17:27:23.32 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.32 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
06/27 17:27:23.32 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins]getPluginPATH
06/27 17:27:23.32 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
06/27 17:27:23.32 INFO setDownloadAlias DriveFileMount :map[]
06/27 17:27:23.33 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
06/27 17:27:23.33 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
06/27 17:27:23.33 INFO start detect platform
06/27 17:27:23.33 INFO Detector.Detect envPlatform:群晖
06/27 17:27:23.33 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
2024/06/27 17:27:23 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/06/27 17:27:23 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
```

如果不动数据直接回退 3.7.1 则启动正常：

```yaml
version: "3"
services:
  xunlei:
    image: cnk3x/xunlei:3.7.1
    privileged: true
    container_name: xunlei
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
      - XL_WEB_PORT=5056
      - XL_DEBUG=true
      - XL_PREVENT_UPDATE=false
    volumes:
      - /mnt/core/app/xunlei:/xunlei/data
      - /mnt/resource/Xunlei:/xunlei/downloads
    restart: unless-stopped
```

**Comment by cnk3x** [comment]
更新修复了一些问题，可以重新拉取试试。

**Comment by sgpublic** [comment]
latest 镜像可以了：
```yaml
version: "3"
services:
  xunlei:
    # image: cnk3x/xunlei:3.7.1
    # image: cnk3x/xunlei:3.11.2
    image: cnk3x/xunlei:latest
    privileged: true
    container_name: xunlei
    network_mode: host
    environment:
      # - UID=1000
      # - GID=1000
      # - XL_WEB_PORT=5056
      - XL_UID=1000
      - XL_GID=1000
      - XL_DASHBOARD_PORT=5056
      - XL_DEBUG=true
      - XL_PREVENT_UPDATE=false
      # - XL_DIR_DATA=/xunlei/data
      # - XL_DIR_DOWNLOAD=/xunlei/downloads
    volumes:
      - /mnt/core/app/xunlei:/xunlei/data
      - /mnt/resource/Xunlei:/xunlei/downloads
    restart: unless-stopped
```

还有问题的话我再开 issue，大佬nb（doge
