### ISSUE TITLE
Docker镜像手动停止后无法再次启动问题

### ISSUE THREAD

**Issue by anonymous5l** [cnk3x/xunlei#168]
起因：
手动将容器停止后再开启就会出现如下错误导致无法启动程序。

解决方案：
删除容器目录内`<容器文件目录>/var/packages/pan-xunlei-com/target/var`下的所有文件，再重新启动即可。

错误日志：
```txt
07/08 17:00:07 ERR [xunlei-pan-cli] Lockfile TryLock err:Locked by other process
07/08 17:00:07 ERR [xunlei-pan-cli] - panic: Locked by other process
07/08 17:00:07 ERR [xunlei-pan-cli] -
07/08 17:00:07 ERR [xunlei-pan-cli] - goroutine 1 [running]:
07/08 17:00:07 ERR [xunlei-pan-cli] - main.Lockfile()
07/08 17:00:07 ERR [xunlei-pan-cli] - 	/xunlei-pan-cli/cmd/pan-cli-launcher/main.go:1099 +0x1cd
07/08 17:00:07 ERR [xunlei-pan-cli] - main.main()
07/08 17:00:07 ERR [xunlei-pan-cli] - 	/xunlei-pan-cli/cmd/pan-cli-launcher/main.go:1127 +0x125
07/08 17:00:07 INF [xunlei-pan-cli] readlog done
07/08 17:00:07 ERR [xunlei-pan-cli] exited err="exit status 2"
07/08 17:00:07 ERR [main] exited! err="exit status 2"
```

建议：
在`/bin/xlp`程序内启动的时候加入清空`<容器文件目录>/var/packages/pan-xunlei-com/target/var`目录下所有文件的功能。

**Comment by chrisuhg** [comment]
俺也一样，我用 compose 起的，直接重建比较快

**Comment by cnk3x** [comment]
好的。

**Comment by cnk3x** [comment]
已修改
