### ISSUE TITLE
貌似有 panic 报错

### ISSUE THREAD

**Issue by LittleNewton** [cnk3x/xunlei#172]
log 如下：

```log
07/16 07:16:25 INF [main] check current user uid=0 gid=0
07/16 07:16:31 INF [main] _  _ _  _ _  _ _    ____  _
07/16 07:16:31 INF [main]  \/  |  | |\ | |    |___  |
07/16 07:16:31 INF [main] _/\_ |__| | \| |___ |___  |
07/16 07:16:31 INF [main] daemon version: v3.20.1
07/16 07:16:31 INF [main] spk version: 3.21.0
07/16 07:16:31 INF [main] port: 2345
07/16 07:16:31 INF [main] ip: <nil>
07/16 07:16:31 INF [main] dashboard username: 
07/16 07:16:31 INF [main] dashboard password: 
07/16 07:16:31 INF [main] dir download: /xunlei/downloads
07/16 07:16:31 INF [main] dir data: /xunlei/data
07/16 07:16:31 INF [main] uid: 0
07/16 07:16:31 INF [main] gid: 0
07/16 07:16:31 INF [main] prevent update: true
07/16 07:16:31 INF [main] chroot: /
07/16 07:16:31 INF [main] debug: false
07/16 07:16:31 INF [main] args: "--dashboard_port" "2345" "--dir_download" "/xunlei/downloads" "--dir_data" "/xunlei/data" "--prevent_update" "--chroot" "/"
07/16 07:16:31 INF [mock] web started listen=[::]:2345
07/16 07:16:31 INF [xunlei-pan-cli] start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.amd64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -update_url http://127.0.0.1:2345/webman/3rdparty/pan-xunlei-com/version"
07/16 07:16:31 INF [xunlei-pan-cli] started pid=19
07/16 07:16:31 WRN [xunlei-pan-cli] > loadHistory ReadFile err:open /xunlei/data/.drive/bin/.history: no such file or directory path:/xunlei/data/.drive/bin/.history
07/16 07:16:31 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:16:31 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:16:31 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
07/16 07:16:31 WRN [xunlei-pan-cli] panic: platform not suport:
07/16 07:16:31 WRN [xunlei-pan-cli] 
07/16 07:16:31 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:16:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:16:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:16:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:16:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:16:31 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
07/16 07:16:31 WRN [xunlei-pan-cli] 
07/16 07:16:31 WRN [xunlei-pan-cli] [panCliPid=38] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
07/16 07:16:31 WRN [xunlei-pan-cli] 
07/16 07:16:31 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:16:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:16:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:16:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:16:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:16:31 WRN [xunlei-pan-cli]  repErr:exit status 2
07/16 07:16:31 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
07/16 07:16:31 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 1
07/16 07:16:32 WRN [xunlei-pan-cli] [report=true&panCliPid=38] > CheckProcess Signal err:os: process already finished
07/16 07:16:51 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:16:51 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:16:52 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
07/16 07:16:52 WRN [xunlei-pan-cli] panic: platform not suport:
07/16 07:16:52 WRN [xunlei-pan-cli] 
07/16 07:16:52 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:16:52 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:16:52 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:16:52 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:16:52 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:16:52 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
07/16 07:16:52 WRN [xunlei-pan-cli] 
07/16 07:16:52 WRN [xunlei-pan-cli] [panCliPid=56] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
07/16 07:16:52 WRN [xunlei-pan-cli] 
07/16 07:16:52 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:16:52 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:16:52 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:16:52 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:16:52 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:16:52 WRN [xunlei-pan-cli]  repErr:exit status 2
07/16 07:16:52 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
07/16 07:16:52 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 2
07/16 07:16:52 WRN [xunlei-pan-cli] [report=true&panCliPid=56] > CheckProcess Signal err:os: process already finished
07/16 07:17:07 WRN [xunlei-pan-cgi] > DetectPlatform err:synology not suport docker name:synology
07/16 07:17:07 WRN [xunlei-pan-cgi] panic: platform not suport:
07/16 07:17:07 WRN [xunlei-pan-cgi] 
07/16 07:17:07 WRN [xunlei-pan-cgi] goroutine 1 [running]:
07/16 07:17:07 WRN [xunlei-pan-cgi] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:17:07 WRN [xunlei-pan-cgi] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:17:07 WRN [xunlei-pan-cgi] main.init.0()
07/16 07:17:07 WRN [xunlei-pan-cgi] 	/xunlei-pan-cli/package/synology/src/ui/amaze.go:8352 +0xf11
07/16 07:17:07 WRN [xunlei-pan-cgi] cgicgi: no headers
07/16 07:17:22 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:17:22 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:17:22 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
07/16 07:17:22 WRN [xunlei-pan-cli] panic: platform not suport:
07/16 07:17:22 WRN [xunlei-pan-cli] 
07/16 07:17:22 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:17:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:17:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:17:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:17:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:17:22 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
07/16 07:17:22 WRN [xunlei-pan-cli] 
07/16 07:17:22 WRN [xunlei-pan-cli] [panCliPid=91] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
07/16 07:17:22 WRN [xunlei-pan-cli] 
07/16 07:17:22 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:17:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:17:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:17:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:17:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:17:22 WRN [xunlei-pan-cli]  repErr:exit status 2
07/16 07:17:22 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
07/16 07:17:22 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 3
07/16 07:17:23 WRN [xunlei-pan-cli] [panCliPid=91&report=true] > CheckProcess Signal err:os: process already finished
07/16 07:18:02 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:18:02 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:18:02 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
07/16 07:18:02 WRN [xunlei-pan-cli] panic: platform not suport:
07/16 07:18:02 WRN [xunlei-pan-cli] 
07/16 07:18:02 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:18:02 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:18:02 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:18:02 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:18:02 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:18:02 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
07/16 07:18:02 WRN [xunlei-pan-cli] 
07/16 07:18:02 WRN [xunlei-pan-cli] [panCliPid=108] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
07/16 07:18:02 WRN [xunlei-pan-cli] 
07/16 07:18:02 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:18:02 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:18:02 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:18:02 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:18:02 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:18:02 WRN [xunlei-pan-cli]  repErr:exit status 2
07/16 07:18:02 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
07/16 07:18:02 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 4
07/16 07:18:03 WRN [xunlei-pan-cli] [report=true&panCliPid=108] > CheckProcess Signal err:os: process already finished
07/16 07:18:52 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:18:52 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.6 INFO  > run 3.21.0 /xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 [--logsize 10MB --pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child --info /var/packages/pan-xunlei-com/target/bin/bin/info.file -q run runner]
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.6 INFO [panCliPath=/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64&panCliPid=129&env=["LauncherAddress=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME=cde685989301","XL_CHROOT=/","LANG=zh_CN.UTF-8","LANGUAGE=zh_CN.UTF-8","LC_ALL=C","XL_DEBUG=false","XL_DASHBOARD_PORT=2345","XL_DASHBOARD_USERNAME=","XL_DIR_DOWNLOAD=/xunlei/downloads","XL_DIR_DATA=/xunlei/data","XL_DASHBOARD_PASSWORD=","XL_PREVENT_UPDATE=true","XL_UID=","XL_GID=","SYNOPLATFORM=geminilake","SYNOPKG_PKGNAME=pan-xunlei-com","SYNOPKG_PKGVER=3.21.0","SYNOPKG_PKGDEST=/var/packages/pan-xunlei-com/target","SYNOPKG_DSM_VERSION_MAJOR=7","SYNOPKG_DSM_VERSION_MINOR=2","SYNOPKG_DSM_VERSION_BUILD=64570","DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock","PLATFORM=群晖","OS_VERSION=geminilake dsm 7.2-64570","ConfigPath=/xunlei/data","HOME=/xunlei/data/.drive","DownloadPATH=/xunlei/downloads","TLSInsecureSkipVerify=true","GIN_MODE=release","BinDir=/xunlei/data/.drive/bin"]] > launcher start to run client
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO  > loadenv from /xunlei/data/.drive/bin
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO [error={"Op":"open","Path":"/xunlei/data/.drive/bin/envconfig","Err":2}&file=/xunlei/data/.drive/bin/envconfig] > read envconfig failed use default
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO [device_space=&config_path=/xunlei/data/.drive/] > use config
07/16 07:18:52 INF [xunlei-pan-cli] getEnvs succ DownloadPATH=/xunlei/downloads
07/16 07:18:52 INF [xunlei-pan-cli] getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
07/16 07:18:52 INF [xunlei-pan-cli] getEnvs succ PLATFORM=群晖
07/16 07:18:52 INF [xunlei-pan-cli] getEnvs succ ConfigPath=/xunlei/data
07/16 07:18:52 INF [xunlei-pan-cli] getEnvs succ TLSInsecureSkipVerify=true
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO [device_space=&config_path=/xunlei/data/.drive/] > use config
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO [use_path=/xunlei/data/.drive/plugins&report=true] > getPluginPATH
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO [device_space=&config_path=/xunlei/data/.drive/] > use config
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO  > setDownloadAlias DriveFileMount :map[]
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO  > config.init getEnvStrArray DownloadPATH:[/xunlei/downloads] len:1
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO  > config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/xunlei/data/.drive/bin Platform:群晖 PathSplit:: DownloadPATHs:[/xunlei/downloads] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/xunlei/data/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/xunlei/data DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 IdleMemoryUsageLimit:272629760 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/xunlei/data/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO  > start detect platform
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 INFO  > Detector.Detect envPlatform:群晖
07/16 07:18:52 INF [xunlei-pan-cli] 07/16 07:18:52.8 ERROR  > DetectPlatform err:synology not suport docker name:synology
07/16 07:18:52 INF [xunlei-pan-cli] panic: platform not suport:
07/16 07:18:52 INF [xunlei-pan-cli] 
07/16 07:18:52 INF [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:18:52 INF [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:18:52 INF [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:18:52 INF [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:18:52 INF [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:18:52 INF [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
07/16 07:18:52 INF [xunlei-pan-cli] 
07/16 07:18:52 WRN [xunlei-pan-cli] [panCliPid=129] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
07/16 07:18:52 WRN [xunlei-pan-cli] 
07/16 07:18:52 WRN [xunlei-pan-cli] goroutine 1 [running]:
07/16 07:18:52 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
07/16 07:18:52 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
07/16 07:18:52 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
07/16 07:18:52 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
07/16 07:18:52 WRN [xunlei-pan-cli]  repErr:exit status 2
07/16 07:18:52 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
07/16 07:18:52 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 5
```

## 环境信息

docker version: `27.0.3`
OS: `debian 12`
Kernel: `linux-6.1`

## 安装方式

```bash
docker run -e XL_CHROOT=/ -v ./data:/xunlei/data -v ./downloads:/xunlei/downloads -p 2345:2345 cnk3x/xunlei
```

## 存储驱动

``` bash
# docker info | grep "Storage Driver"
 Storage Driver: overlay2
[DEPRECATION NOTICE]: API is accessible on http://10.2.4.21:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
In future versions this will be a hard failure preventing the daemon from starting! Learn more at: https://docs.docker.com/go/api-security/
```

**Comment by LittleNewton** [comment]
切换为特权模式，问题就解决了。

**Comment by qwerty00007** [comment]
你可以试试给加一个 SYS_ADMIN 的capabilities
我在 truenas 上写的应用加了这条，可以不用特权模式，
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]

**Comment by cnk3x** [comment]
overlay2 存储模式如果不用特权模式运行（指定了 XL_CHROOT=/），会被迅雷检测到容器中运行。所以会panic。你的docker环境只能以特权模式运行。

**Comment by LittleNewton** [comment]
@cnk3x 感谢提供支持。
