### ISSUE TITLE
unraid环境docker 容器报错 怎么解决啊  memory usage limit rss > idle_rss_limit内存超出限制吗？

### ISSUE THREAD

**Issue by ybjopq007** [cnk3x/xunlei#194]
设备内存是16g 容器运行占用也就几百mb 频繁报错卡死 必须手动重启才能运行

下附日志
text  error  warn  system  array  login  
10/09 12:11:53 WRN [xunlei-pan-cli] [out_memory_times=68&rssMB=396&device_space=&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:11:53 INF [xunlei-pan-cli] [rssMB=396&device_space=&idle_rss_limit=260&memOut=68] > memory usage out of limit
10/09 12:12:23 WRN [xunlei-pan-cli] [out_memory_times=69&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:12:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=69] > memory usage out of limit
10/09 12:12:53 WRN [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&out_memory_times=70&device_space=] > memory usage limit rss > idle_rss_limit
10/09 12:12:53 INF [xunlei-pan-cli] [idle_rss_limit=260&device_space=&memOut=70&rssMB=396] > memory usage out of limit
10/09 12:13:23 WRN [xunlei-pan-cli] [device_space=&rssMB=396&out_memory_times=71&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:13:23 INF [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&memOut=71&device_space=] > memory usage out of limit
10/09 12:13:53 WRN [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&out_memory_times=72&device_space=] > memory usage limit rss > idle_rss_limit
10/09 12:13:53 INF [xunlei-pan-cli] [idle_rss_limit=260&device_space=&memOut=72&rssMB=396] > memory usage out of limit
10/09 12:14:23 WRN [xunlei-pan-cli] [out_memory_times=73&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:14:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=73] > memory usage out of limit
10/09 12:14:53 WRN [xunlei-pan-cli] [rssMB=396&out_memory_times=74&idle_rss_limit=260&device_space=] > memory usage limit rss > idle_rss_limit
10/09 12:14:53 INF [xunlei-pan-cli] [idle_rss_limit=260&device_space=&memOut=74&rssMB=396] > memory usage out of limit
10/09 12:15:23 WRN [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&out_memory_times=75] > memory usage limit rss > idle_rss_limit
10/09 12:15:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=75] > memory usage out of limit
10/09 12:15:53 INF [xunlei-pan-cli] 10/09 12:15:53.8 ERROR  download_runner/upload.go:137 [out_memory_times=76&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:15:53 INF [xunlei-pan-cli] 10/09 12:15:53.8 WARNING  download_runner/upload.go:147 [memOut=76&device_space=&rssMB=396&idle_rss_limit=260] > memory usage out of limit
10/09 12:23:53 WRN [xunlei-pan-cli] [idle_rss_limit=260&device_space=&rssMB=396&out_memory_times=92] > memory usage limit rss > idle_rss_limit
10/09 12:23:53 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=92] > memory usage out of limit
10/09 12:24:23 WRN [xunlei-pan-cli] [out_memory_times=93&rssMB=396&device_space=&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:24:23 INF [xunlei-pan-cli] [rssMB=396&device_space=&idle_rss_limit=260&memOut=93] > memory usage out of limit
10/09 12:24:53 WRN [xunlei-pan-cli] [rssMB=396&device_space=&idle_rss_limit=260&out_memory_times=94] > memory usage limit rss > idle_rss_limit
10/09 12:24:53 INF [xunlei-pan-cli] [rssMB=396&device_space=&idle_rss_limit=260&memOut=94] > memory usage out of limit
10/09 12:25:23 WRN [xunlei-pan-cli] [out_memory_times=95&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:25:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=95] > memory usage out of limit
10/09 12:25:53 WRN [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&device_space=&out_memory_times=96] > memory usage limit rss > idle_rss_limit
10/09 12:25:53 INF [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&memOut=96&device_space=] > memory usage out of limit
10/09 12:26:23 WRN [xunlei-pan-cli] [idle_rss_limit=260&out_memory_times=97&device_space=&rssMB=396] > memory usage limit rss > idle_rss_limit
10/09 12:26:23 INF [xunlei-pan-cli] [idle_rss_limit=260&device_space=&rssMB=396&memOut=97] > memory usage out of limit
10/09 12:26:53 WRN [xunlei-pan-cli] [out_memory_times=98&rssMB=396&idle_rss_limit=260&device_space=] > memory usage limit rss > idle_rss_limit
10/09 12:26:53 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=98] > memory usage out of limit
10/09 12:27:23 WRN [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&out_memory_times=99] > memory usage limit rss > idle_rss_limit
10/09 12:27:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=99] > memory usage out of limit
10/09 12:27:53 WRN [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&out_memory_times=100] > memory usage limit rss > idle_rss_limit
10/09 12:27:53 INF [xunlei-pan-cli] [rssMB=396&memOut=100&idle_rss_limit=260&device_space=] > memory usage out of limit
10/09 12:28:23 WRN [xunlei-pan-cli] [out_memory_times=101&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:28:23 INF [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&memOut=101&device_space=] > memory usage out of limit
10/09 12:28:53 WRN [xunlei-pan-cli] [out_memory_times=102&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:28:53 INF [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&memOut=102&device_space=] > memory usage out of limit
10/09 12:29:23 WRN [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&out_memory_times=103] > memory usage limit rss > idle_rss_limit
10/09 12:29:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=103] > memory usage out of limit
10/09 12:29:53 WRN [xunlei-pan-cli] [rssMB=396&device_space=&idle_rss_limit=260&out_memory_times=104] > memory usage limit rss > idle_rss_limit
10/09 12:29:53 INF [xunlei-pan-cli] [device_space=&idle_rss_limit=260&memOut=104&rssMB=396] > memory usage out of limit
10/09 12:30:23 WRN [xunlei-pan-cli] [out_memory_times=105&rssMB=396&idle_rss_limit=260&device_space=] > memory usage limit rss > idle_rss_limit
10/09 12:30:23 INF [xunlei-pan-cli] [idle_rss_limit=260&memOut=105&device_space=&rssMB=396] > memory usage out of limit
10/09 12:30:53 WRN [xunlei-pan-cli] [device_space=&idle_rss_limit=260&out_memory_times=106&rssMB=396] > memory usage limit rss > idle_rss_limit
10/09 12:30:53 INF [xunlei-pan-cli] [memOut=106&rssMB=396&device_space=&idle_rss_limit=260] > memory usage out of limit
10/09 12:31:23 WRN [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&out_memory_times=107] > memory usage limit rss > idle_rss_limit
10/09 12:31:23 INF [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&device_space=&memOut=107] > memory usage out of limit
10/09 12:31:53 WRN [xunlei-pan-cli] [out_memory_times=108&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:31:53 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=108] > memory usage out of limit
10/09 12:32:23 WRN [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&device_space=&out_memory_times=109] > memory usage limit rss > idle_rss_limit
10/09 12:32:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&idle_rss_limit=260&memOut=109] > memory usage out of limit
10/09 12:32:53 WRN [xunlei-pan-cli] [rssMB=396&idle_rss_limit=260&device_space=&out_memory_times=110] > memory usage limit rss > idle_rss_limit
10/09 12:32:53 INF [xunlei-pan-cli] [memOut=110&device_space=&rssMB=396&idle_rss_limit=260] > memory usage out of limit
10/09 12:33:23 WRN [xunlei-pan-cli] [device_space=&rssMB=400&idle_rss_limit=260&out_memory_times=111] > memory usage limit rss > idle_rss_limit
10/09 12:33:23 INF [xunlei-pan-cli] [device_space=&memOut=111&rssMB=400&idle_rss_limit=260] > memory usage out of limit
10/09 12:33:44 INF [xunlei-pan-cli] 10/09 12:33:44.5 INFO  > get version list [] map[arch:amd64 client_id:X9ibISwpIp8jQ4Ya client_version:3.21.0 device_id:a7fd019efdc72fa27258d7b3c996ab94 hour:12 package_name:pan.xunlei.cli.synology platform:synology user_id:202587629]
10/09 12:33:44 INF [xunlei-pan-cli] 10/09 12:33:44.5 INFO  service/logger.go:72 [request=/device/healthz&duration=0.000510497&comment=&xllite_trace_id=9vTUP7ZB&clientIP=&method=GET&status=200] > api.request
10/09 12:33:53 WRN [xunlei-pan-cli] [device_space=&rssMB=401&idle_rss_limit=260&out_memory_times=112] > memory usage limit rss > idle_rss_limit
10/09 12:33:53 INF [xunlei-pan-cli] [device_space=&rssMB=401&idle_rss_limit=260&memOut=112] > memory usage out of limit
10/09 12:34:23 WRN [xunlei-pan-cli] [idle_rss_limit=260&out_memory_times=113&device_space=&rssMB=401] > memory usage limit rss > idle_rss_limit
10/09 12:34:23 INF [xunlei-pan-cli] [device_space=&rssMB=401&idle_rss_limit=260&memOut=113] > memory usage out of limit
10/09 12:34:53 WRN [xunlei-pan-cli] [out_memory_times=114&rssMB=401&idle_rss_limit=260&device_space=] > memory usage limit rss > idle_rss_limit
10/09 12:34:53 INF [xunlei-pan-cli] [idle_rss_limit=260&memOut=114&device_space=&rssMB=401] > memory usage out of limit
10/09 12:35:23 WRN [xunlei-pan-cli] [device_space=&rssMB=399&idle_rss_limit=260&out_memory_times=115] > memory usage limit rss > idle_rss_limit
10/09 12:35:23 INF [xunlei-pan-cli] [memOut=115&device_space=&rssMB=399&idle_rss_limit=260] > memory usage out of limit
10/09 12:35:53 WRN [xunlei-pan-cli] [idle_rss_limit=260&device_space=&out_memory_times=116&rssMB=399] > memory usage limit rss > idle_rss_limit
10/09 12:35:53 INF [xunlei-pan-cli] [idle_rss_limit=260&memOut=116&device_space=&rssMB=399] > memory usage out of limit
10/09 12:36:23 WRN [xunlei-pan-cli] [device_space=&rssMB=399&idle_rss_limit=260&out_memory_times=117] > memory usage limit rss > idle_rss_limit
10/09 12:36:23 INF [xunlei-pan-cli] [memOut=117&idle_rss_limit=260&device_space=&rssMB=399] > memory usage out of limit
10/09 12:36:53 WRN [xunlei-pan-cli] [out_memory_times=118&device_space=&rssMB=399&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:36:53 INF [xunlei-pan-cli] [device_space=&rssMB=399&idle_rss_limit=260&memOut=118] > memory usage out of limit
10/09 12:37:23 WRN [xunlei-pan-cli] [out_memory_times=119&device_space=&rssMB=396&idle_rss_limit=260] > memory usage limit rss > idle_rss_limit
10/09 12:37:23 INF [xunlei-pan-cli] [device_space=&rssMB=396&memOut=119&idle_rss_limit=260] > memory usage out of limit
10/09 12:37:53 WRN [xunlei-pan-cli] [device_space=&rssMB=395&idle_rss_limit=260&out_memory_times=120] > memory usage limit rss > idle_rss_limit
10/09 12:37:53 INF [xunlei-pan-cli] [device_space=&rssMB=395&idle_rss_limit=260&memOut=120] > memory usage out of limit
10/09 12:37:53 WRN [xunlei-pan-cli] [idle_rss_limit=260&memOut=120&device_space=&rssMB=395] > memory usage out of limit panic
10/09 12:37:53 WRN [xunlei-pan-cli] panic: idle memory usage out of limit
10/09 12:37:53 WRN [xunlei-pan-cli] 
10/09 12:37:53 WRN [xunlei-pan-cli] goroutine 72 [running]:
10/09 12:37:53 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/download_runner.ProcessStat(0xc0005ab400)
10/09 12:37:53 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/download_runner/upload.go:153 +0xa2d
10/09 12:37:53 WRN [xunlei-pan-cli] created by gitlab.xunlei.cn/xlppc/pan-cli/pkg/commands.StartDeviceRunner
10/09 12:37:53 WRN [xunlei-pan-cli]     /xunlei-pan-cli/pkg/commands/runner.go:80 +0xb6
10/09 12:37:54 WRN [xunlei-pan-cli] [report=true&panCliPid=50] > CheckProcess Signal err:os: process already finished
10/09 12:37:54 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:os: process already finished
10/09 12:38:04 WRN [xunlei-pan-cli] > killPid process.Signal SIGABRT err:os: process already finished
10/09 12:38:04 INF [xunlei-pan-cli] > kill process error:os: process already finished

**Comment by Mr-Jies** [comment]
也遇到了，求解决方案

**Comment by ybjopq007** [comment]
> > 也遇到了，求解决方案
> 
> 增加容器内存限制 在您的 docker-compose.yml 文件中，您可以为涉及的服务设置更高的内存限制。例如：
> 
> version: '3' services: xunlei-pan-cli: image: your-image-name deploy: resources: limits: memory: 512M …
> 
> 这里将内存限制设置为 512MB，可以根据您的应用需求调整大小。

并没有什么用 下点东西一点容器卡死八百回
