### ISSUE TITLE
非特权模式无法启动（panic: platform not suport）

### ISSUE THREAD

**Issue by FengZhongShaoNian** [cnk3x/xunlei#199]
docker-compose.yml文件如下：
```yml
services:
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    restart: unless-stopped
    environment:
      XL_CHROOT: /
      XL_DASHBOARD_USERNAME: xxx
      XL_DASHBOARD_PASSWORD: xxxxxxxx
      XL_UID: 1000
      XL_GID: 1000 
    ports:
      - 2345:2345
    volumes:
      - ./data:/xunlei/data
      - ./下载:/xunlei/downloads
```

docker日志如下：
```
10/27 16:20:21 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:20:21 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:20:21 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:20:21 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:20:21 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:20:21 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
10/27 16:20:21 WRN [xunlei-pan-cli] 
10/27 16:20:21 WRN [xunlei-pan-cli] [panCliPid=28] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
10/27 16:20:21 WRN [xunlei-pan-cli] 
10/27 16:20:21 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:20:21 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:20:21 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:20:21 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:20:21 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:20:21 WRN [xunlei-pan-cli]  repErr:exit status 2
10/27 16:20:21 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
10/27 16:20:21 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 2
10/27 16:20:21 WRN [xunlei-pan-cli] [panCliPid=28&report=true] > CheckProcess Signal err:os: process already finished
10/27 16:20:51 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:20:51 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:20:51 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
10/27 16:20:51 WRN [xunlei-pan-cli] panic: platform not suport:
10/27 16:20:51 WRN [xunlei-pan-cli] 
10/27 16:20:51 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:20:51 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:20:51 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:20:51 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:20:51 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:20:51 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
10/27 16:20:51 WRN [xunlei-pan-cli] 
10/27 16:20:51 WRN [xunlei-pan-cli] [panCliPid=34] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
10/27 16:20:51 WRN [xunlei-pan-cli] 
10/27 16:20:51 WRN[0m [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:20:51 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:20:51 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:20:51 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:20:51 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:20:51 WRN [xunlei-pan-cli]  repErr:exit status 2
10/27 16:20:51 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
10/27 16:20:51 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 3
10/27 16:20:52 WRN [xunlei-pan-cli] [report=true&panCliPid=34] > CheckProcess Signal err:os: process already finished
10/27 16:21:31 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:21:31 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:21:31 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
10/27 16:21:31 WRN [xunlei-pan-cli] panic: platform not suport:
10/27 16:21:31 WRN [xunlei-pan-cli] 
10/27 16:21:31 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:21:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:21:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:21:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:21:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:21:31 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
10/27 16:21:31 WRN [xunlei-pan-cli] 
10/27 16:21:31 WRN [xunlei-pan-cli] [panCliPid=41] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
10/27 16:21:31 WRN [xunlei-pan-cli] 
10/27 16:21:31 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:21:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:21:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:21:31 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:21:31 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:21:31 WRN [xunlei-pan-cli]  repErr:exit status 2
10/27 16:21:31 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
10/27 16:21:31 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 4
10/27 16:21:32 WRN [xunlei-pan-cli] [report=true&panCliPid=41] > CheckProcess Signal err:os: process already finished
10/27 16:22:21 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:22:21 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:22:21 WRN [xunlei-pan-cli] [panCliPid=47] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
10/27 16:22:21 WRN [xunlei-pan-cli] 
10/27 16:22:21 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:22:21 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:22:21 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:22:21 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:22:21 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:22:21 WRN [xunlei-pan-cli]  repErr:exit status 2
10/27 16:22:21 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
10/27 16:22:21 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 5
10/27 16:22:22 WRN [xunlei-pan-cli] [report=true&panCliPid=47] > CheckProcess Signal err:os: process already finished
10/27 16:23:21 WRN [xunlei-pan-cli] > KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:23:21 INF [xunlei-pan-cli] > kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
10/27 16:23:22 WRN [xunlei-pan-cli] > DetectPlatform err:synology not suport docker name:synology
10/27 16:23:22 WRN [xunlei-pan-cli] panic: platform not suport:
10/27 16:23:22 WRN [xunlei-pan-cli] 
10/27 16:23:22 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:23:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:23:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:23:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:23:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:23:22 WRN [xunlei-pan-cli] report log {"fields":{"error":"exit status 2","panic":"panic: platform not suport:\n\ngoroutine 1 [running]:\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()\n\t/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9\ngitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()\n\t/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11\n","report_type":"launcher"}}
10/27 16:23:22 WRN [xunlei-pan-cli] 
10/27 16:23:22 WRN [xunlei-pan-cli] [panCliPid=52] > Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/xunlei/data/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: platform not suport:
10/27 16:23:22 WRN [xunlei-pan-cli] 
10/27 16:23:22 WRN [xunlei-pan-cli] goroutine 1 [running]:
10/27 16:23:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
10/27 16:23:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
10/27 16:23:22 WRN [xunlei-pan-cli] gitlab.xunlei.cn/xlppc/pan-cli/pkg/oauth2client.init.0()
10/27 16:23:22 WRN [xunlei-pan-cli] 	/xunlei-pan-cli/pkg/oauth2client/algorithms.go:8324 +0xf11
10/27 16:23:22 WRN [xunlei-pan-cli]  repErr:exit status 2
10/27 16:23:22 WRN [xunlei-pan-cli] > start new version 3.21.0=>3.21.0 err:exit status 2
10/27 16:23:22 INF [xunlei-pan-cli] > launcher version error exit status 2 retry 6
10/27 16:23:22 WRN [xunlei-pan-cli] [report=true&panCliPid=52] > CheckProcess Signal err:os: process already finished

```

我的docker的存储驱动使用的是btrfs:
```
Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 27.3.1
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
```

**Comment by realabertian** [comment]
我的是overlay2 也没法在非特权模式下启动

**Comment by sangemajia** [comment]
https://github.com/cnk3x/xunlei/issues/108
这里给了非特权模式的解决方案 使用--cap-add SYS_ADMIN来控制权限
