### ISSUE TITLE
更新3.3.1了，请大佬更新。

### ISSUE THREAD

**Issue by hyy34** [cnk3x/xunlei#67]
又开始自动更新-502循环了，发现现在已经是3.3.1的版本了，请求大佬更新，或者阻止后台自动更新。

**Comment by dragonflylee** [comment]
建议添加 `-e XL_DEBUG=1` 环境变量 查看详细出错日志

**Comment by dragonflylee** [comment]
添加 host 屏蔽更新也是办法 `-add-host 2rvk4e3gkdnl7u1kl0k.xbase.cloud:127.0.0.1`

**Comment by hyy34** [comment]
> -add-host 2rvk4e3gkdnl7u1kl0k.xbase.cloud:127.0.0.1

2023-02-07T08:15:51.422707473Z INFO set log level: info
2023-02-07T08:15:51.442555506Z INFO  biz/manager.go:547 [report=true&WorkDir=/data/.drive/plugins]NewPluginManager
2023-02-07T08:15:51.442778466Z INFO  biz/manager.go:130 [pluginSmInfo=&report=true&pluginPath=/data/.drive/plugins/6a7ce3356c4740946df70760d8fa97bd/v1.0.0/6a7ce3356c4740946df70760d8fa97bd]LoadPlugin
2023-02-07T08:15:51.446705476Z WARNING  data/plugin.go:344 killProcess syscall.Kill err:no such process req:/scripts/stop.sh
welcome to speed-test.
PluginWorkDir: /data/.drive/plugins/6a7ce3356c4740946df70760d8fa97bd/v1.0.0/6a7ce3356c4740946df70760d8fa97bd
ready to start...
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
[GIN-debug] GET    /upload                   --> main.main.func1 (6 handlers)
[GIN-debug] GET    /data                     --> main.main.func2 (6 handlers)
[GIN-debug] GET    /main_page                --> main.main.func3 (6 handlers)
[GIN-debug] GET    /dist/*filepath           --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (6 handlers)
[GIN-debug] HEAD   /dist/*filepath           --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (6 handlers)
2023/02/07 16:15:51 demo wd:/data
2023/02/07 16:15:51 demo PluginWorkDir:/data/.drive/plugins/6a7ce3356c4740946df70760d8fa97bd/v1.0.0/6a7ce3356c4740946df70760d8fa97bd
2023/02/07 16:15:51 demo uiPort:40593
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :40593
2023-02-07T08:15:51.581793595Z INFO  oauth2client/client.go:368 [report_type=request&method=GET&duration=257.675862&lookup=addr:xluser-ssl.xunlei.com ip:47.100.173.19547.103.14.382408:4002:1f10::25a&url=https://xluser-ssl.xunlei.com/v1/user/me]Client.Request
2023-02-07T08:15:51.581911856Z INFO  oauth2client/client.go:241 client.Request succ! url:https://xluser-ssl.xunlei.com/v1/user/me
refresh dy1-vip-ssl.xunlei.com
add peer 101.133.168.165 net.IP{0x65, 0x85, 0xa8, 0xa5}
add peer 2408:4002:1f10::109 net.IP{0x24, 0x8, 0x40, 0x2, 0x1f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x9}
2023-02-07T08:15:51.836221044Z INFO  oauth2client/client.go:368 [duration=253.175842&report_type=request&method=GET&url=https://dy1-vip-ssl.xunlei.com/logininfo/vipinfo&lookup=addr:dy1-vip-ssl.xunlei.com ip:101.133.168.1652408:4002:1f10::109]Client.Request
2023-02-07T08:15:51.836359437Z INFO  oauth2client/client.go:241 client.Request succ! url:https://dy1-vip-ssl.xunlei.com/logininfo/vipinfo
2023-02-07T08:15:51.83639097Z INFO  drive/client.go:514 [device_space=]update vipinfo {false 1 0 false} <nil> struct { Data struct { Autodeduct string "json:\"autodeduct\""; Daily string "json:\"daily\""; Expire string "json:\"expire\""; Grow string "json:\"grow\""; IsVip string "json:\"isvip\""; IsYear string "json:\"isyear\""; Level string "json:\"level\""; MonthExpire string "json:\"month_expire\""; Payid string "json:\"payid\""; Payname string "json:\"payname\""; Register string "json:\"register\""; Remind string "json:\"remind\""; Userid string "json:\"userid\""; Uservas string "json:\"uservas\""; VasType string "json:\"vas_type\"" } "json:\"data\""; Result int "json:\"result\""; Message string "json:\"message\"" }{Data:struct { Autodeduct string "json:\"autodeduct\""; Daily string "json:\"daily\""; Expire string "json:\"expire\""; Grow string "json:\"grow\""; IsVip string "json:\"isvip\""; IsYear string "json:\"isyear\""; Level string "json:\"level\""; MonthExpire string "json:\"month_expire\""; Payid string "json:\"payid\""; Payname string "json:\"payname\""; Register string "json:\"register\""; Remind string "json:\"remind\""; Userid string "json:\"userid\""; Uservas string "json:\"uservas\""; VasType string "json:\"vas_type\"" }{Autodeduct:"0", Daily:"-10", Expire:"20230126", Grow:"345", IsVip:"0", IsYear:"0", Level:"1", MonthExpire:"20230126", Payid:"0", Payname:"---", Register:"20221226", Remind:"", Userid:"887104843", Uservas:"0", VasType:"3"}, Result:0, Message:"ok"}
2023-02-07T08:15:53.449039535Z INFO  pan-cli/main.go:243 with cookie map[]
2023-02-07T08:15:53.449196702Z ERROR  pan-cli/main.go:264 Cannot lock "/var/packages/pan-xunlei-com/target/bin/pan-cli.pid.child", reason: Locked by other process
panic: Locked by other process
goroutine 91 [running]:
main.startService.func1(0xc002edb080)
	/xunlei-pan-cli/cmd/pan-cli/main.go:265 +0xb2b
github.com/urfave/cli.(*App).Run(0xc003494000, {0xc00003c140, 0xa, 0xa})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:264 +0x56d
main.startService(0xc00300fee0)
	/xunlei-pan-cli/cmd/pan-cli/main.go:309 +0x8e7
created by main.main
	/xunlei-pan-cli/cmd/pan-cli/main.go:64 +0x26a
2023-02-07T08:16:21.232410003Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:8 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T08:16:21.23325065Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:8 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T08:16:21.233584617Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:8 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T08:16:21.234306383Z INFO get version list [{3.3.1 amd64 [2.8.0 2.9.0 2.9.1 2.10.0 2.11.0 2.12.0 2.12.1 2.12.2 3.0.0 3.0.1 3.0.2 3.1.0 3.1.1 3.1.3 3.1.4 3.1.5 3.1.8 3.1.9 3.1.10 3.3.0] false { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["client_version","notIn","0"]}]}] []} 1. 部分功能重构，提高下载和片库稳定性<br/>
2. PC迅雷增加-远程设备入口<br/>
3. 修复若干已知bug
 https://static.xbase.cloud/file/2rvk4e3gkdnl7u1kl0k/pancli/amd64/xunlei-pan-cli.3.3.1-20230202.amd64 41258120}] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:8 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T09:16:21.391037027Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:9 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T09:16:21.391475699Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:9 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T09:16:21.391647676Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:9 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T09:16:21.392025163Z INFO get version list [{3.3.1 amd64 [2.8.0 2.9.0 2.9.1 2.10.0 2.11.0 2.12.0 2.12.1 2.12.2 3.0.0 3.0.1 3.0.2 3.1.0 3.1.1 3.1.3 3.1.4 3.1.5 3.1.8 3.1.9 3.1.10 3.3.0] false { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["client_version","notIn","0"]}]}] []} 1. 部分功能重构，提高下载和片库稳定性<br/>
2. PC迅雷增加-远程设备入口<br/>
3. 修复若干已知bug
 https://static.xbase.cloud/file/2rvk4e3gkdnl7u1kl0k/pancli/amd64/xunlei-pan-cli.3.3.1-20230202.amd64 41258120}] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:9 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T10:16:21.553519778Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:10 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T10:16:21.55416127Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:10 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T10:16:21.554415857Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:10 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T10:16:21.554956952Z INFO get version list [{3.3.1 amd64 [2.8.0 2.9.0 2.9.1 2.10.0 2.11.0 2.12.0 2.12.1 2.12.2 3.0.0 3.0.1 3.0.2 3.1.0 3.1.1 3.1.3 3.1.4 3.1.5 3.1.8 3.1.9 3.1.10 3.3.0] false { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["client_version","notIn","0"]}]}] []} 1. 部分功能重构，提高下载和片库稳定性<br/>
2. PC迅雷增加-远程设备入口<br/>
3. 修复若干已知bug
 https://static.xbase.cloud/file/2rvk4e3gkdnl7u1kl0k/pancli/amd64/xunlei-pan-cli.3.3.1-20230202.amd64 41258120}] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:10 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T11:16:21.713949712Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:11 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T11:16:21.714811863Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:11 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T11:16:21.715160136Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:11 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T11:16:21.715962083Z INFO get version list [{3.3.1 amd64 [2.8.0 2.9.0 2.9.1 2.10.0 2.11.0 2.12.0 2.12.1 2.12.2 3.0.0 3.0.1 3.0.2 3.1.0 3.1.1 3.1.3 3.1.4 3.1.5 3.1.8 3.1.9 3.1.10 3.3.0] false { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["client_version","notIn","0"]}]}] []} 1. 部分功能重构，提高下载和片库稳定性<br/>
2. PC迅雷增加-远程设备入口<br/>
3. 修复若干已知bug
 https://static.xbase.cloud/file/2rvk4e3gkdnl7u1kl0k/pancli/amd64/xunlei-pan-cli.3.3.1-20230202.amd64 41258120}] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:11 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T12:16:21.875653617Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]},{"match":["user_id","in","21093691","6164030","27539667","824122260","666305052","485646","1312415","823080223","841121243","838673700","203448711","808558937","598879425","807105650","108601202","19015111","168050281","646035506","616948044","573771831","106407414","363691814","139205641","801671167","101665307","816517601","26031594","16190062","689725998","44636542","571284367","576030835","15121169","6346319","767914104","228546131","152691506","171022900","131562143","38844","559889892","685406963","105533622","570398050","283020403","171342580","817420806","290158100","577627730","300173215","481287249","7892136","77663059","825157600","6305980","170624275","685613901","73708826","12789032","451492766","657665605","692968250","825667556","88573501","167286179","763572","599141793","60909869","60481318","605729477","574221850","861708","204558","699171656","106407414","579179268","559800335","36682410","254592421","102258030","805088738","20271970","586765","56807891","99351595","1069713","293101160","273548937","757330327","13228003","93790521","398838291","209829499","838406881","256148946","701907977","152691506","816698261","1295108620","1703648411"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:12 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T12:16:21.87583657Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:12 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T12:16:21.875948556Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:12 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T12:16:21.876338445Z INFO get version list [] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:12 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T13:16:22.023563779Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]},{"match":["user_id","in","21093691","6164030","27539667","824122260","666305052","485646","1312415","823080223","841121243","838673700","203448711","808558937","598879425","807105650","108601202","19015111","168050281","646035506","616948044","573771831","106407414","363691814","139205641","801671167","101665307","816517601","26031594","16190062","689725998","44636542","571284367","576030835","15121169","6346319","767914104","228546131","152691506","171022900","131562143","38844","559889892","685406963","105533622","570398050","283020403","171342580","817420806","290158100","577627730","300173215","481287249","7892136","77663059","825157600","6305980","170624275","685613901","73708826","12789032","451492766","657665605","692968250","825667556","88573501","167286179","763572","599141793","60909869","60481318","605729477","574221850","861708","204558","699171656","106407414","579179268","559800335","36682410","254592421","102258030","805088738","20271970","586765","56807891","99351595","1069713","293101160","273548937","757330327","13228003","93790521","398838291","209829499","838406881","256148946","701907977","152691506","816698261","1295108620","1703648411"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:13 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T13:16:22.024145376Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:13 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T13:16:22.024482757Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:13 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T13:16:22.025158958Z INFO get version list [] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:13 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T14:16:22.236286603Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","737602543","190725001","855720291","838406881","228546131","256148940","5860805431"]},{"match":["user_id","in","21093691","6164030","27539667","824122260","666305052","485646","1312415","823080223","841121243","838673700","203448711","808558937","598879425","807105650","108601202","19015111","168050281","646035506","616948044","573771831","106407414","363691814","139205641","801671167","101665307","816517601","26031594","16190062","689725998","44636542","571284367","576030835","15121169","6346319","767914104","228546131","152691506","171022900","131562143","38844","559889892","685406963","105533622","570398050","283020403","171342580","817420806","290158100","577627730","300173215","481287249","7892136","77663059","825157600","6305980","170624275","685613901","73708826","12789032","451492766","657665605","692968250","825667556","88573501","167286179","763572","599141793","60909869","60481318","605729477","574221850","861708","204558","699171656","106407414","579179268","559800335","36682410","254592421","102258030","805088738","20271970","586765","56807891","99351595","1069713","293101160","273548937","757330327","13228003","93790521","398838291","209829499","838406881","256148946","701907977","152691506","816698261","1295108620","1703648411"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:14 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T14:16:22.236451114Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"match":["hour","in","5","6","7","8"]} {"matchAny":[{"match":["user_id","in","737602543","827350621","728680263"]},{"match":["user_id","in","111642007","701875897","838406881"]},{"match":["user_id","hasSuffix","6"]},{"match":["user_id","hasSuffix","7"]},{"match":["user_id","hasSuffix","8"]},{"match":["user_id","hasSuffix","9"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:14 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T14:16:22.236843213Z INFO filter not match { map[] map[] map[] <nil> null [{"match":["platform","in","synology","linux"]} {"matchAny":[{"match":["user_id","in","256148940"]}]}] []} map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:14 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T14:16:22.237021236Z INFO get version list [] map[arch:amd64 client_id: client_version:3.1.10 device_id:7abd3182d399f7bdda199550d8babede hour:14 package_name:pan.xunlei.cli.synology platform:synology user_id:887104843]
2023-02-07T14:29:08.199859885Z INFO loadenv from /var/packages/pan-xunlei-com/target/ui
2023-02-07T14:29:08.199911096Z INFO [error=&file=/var/packages/pan-xunlei-com/target/ui/envconfig]read envconfig failed use default
2023-02-07T14:29:08.199927953Z INFO [config_path=/data/.drive/&device_space=]use config
2023-02-07T14:29:08.225631468Z INFO [device_space=&config_path=/data/.drive/]use config
2023-02-07T14:29:08.235223603Z INFO [use_path=/data/.drive/plugins&report=true]getPluginPATH
2023-02-07T14:29:08.235242718Z INFO setDownloadAlias DriveFileMount :map[]
2023-02-07T14:29:08.235255243Z INFO config.init getEnvStrArray DownloadPATH:[/迅雷下载] len:1
2023-02-07T14:29:08.235290825Z INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform: DownloadPATHs:[/迅雷下载] DriveFileMount:map[] PluginPATH:/data/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveUpdate: DriveConfigPATH: DrivePIDFile: DriveInfoFile: LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h}
2023-02-07T14:29:08.235296162Z INFO start detect platform
2023-02-07T14:29:08.235988055Z ERROR DetectPlatform err:env PLATFORM=lexar:ea94acab567b9cc724e943be3e4ac5c5 not exist name:lexar
2023-02-07T14:29:08.235998583Z ERROR DetectPlatform err:stat /.dockerenv: no such file or directory name:docker
2023-02-07T14:29:08.236004497Z ERROR DetectPlatform err:env PLATFORM=zspace:a68b3d890b860d0165a8f6f66acc6d45 not exist name:zspace
2023-02-07T14:29:08.236262593Z INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect]
2023/02/07 14:29:08 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2023/02/07 14:29:08 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused

**Comment by cnk3x** [comment]
已更新底包到3.4.0
